export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants = {
    
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}

export const categoryConstants = {
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS:'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE:'GET_CATEGORY_FAILURE',
    ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE:'ADD_NEW_CATEGORY_FAILURE'
}

export const productConstants = {
    GET_PRODUCT_REQUEST:'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS:'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE:'GET_PRODUCT_FAILURE',
    ADD_NEW_PRODUCT_REQUEST:'ADD_NEW_PRODUCT_REQUEST',
    ADD_NEW_PRODUCT_SUCCESS:'ADD_NEW_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_FAILURE:'ADD_NEW_PRODUCT_FAILURE'
}

export const initialDataConstants = {
    GET_INITIAL_DATA_REQUEST:'GET_INITIAL_DATA_REQUEST',
    GET_INITIAL_DATA_SUCCESS:'GET_INITIAL_DATA_SUCCESS',
    GET_INITIAL_DATA_FAILURE:'GET_INITIAL_DATA_FAILURE',
}